from _typeshed import Incomplete

from ebenezer.commands.helpers import run_command as run_command

app: Incomplete

def backlight_level() -> None: ...
def backlight_up() -> None: ...
def backlight_down() -> None: ...
def backlight_set(level: int): ...
