from ebenezer.commands.helpers import run_command as run_command

def cli() -> None: ...
def level() -> None: ...
def up() -> None: ...
def down() -> None: ...
def set(level: int): ...
def backlight_level() -> str: ...
def backlight_up() -> None: ...
def backlight_down() -> None: ...
def backlight_set(level: int): ...
