from ebenezer.commands.helpers import run_command as run_command

HEADSET_SINK: str

def get_volume_level() -> str: ...
def get_volume_levels() -> str: ...
def cli() -> None: ...
def level() -> None: ...
def levels() -> None: ...
def up() -> None: ...
def down() -> None: ...
def mute_toggle() -> None: ...
def mute_on() -> None: ...
def mute_off() -> None: ...
def mute_status() -> None: ...
def mute_mic() -> None: ...
def phone_plugged() -> None: ...
def volume_up() -> None: ...
def volume_down() -> None: ...
def volume_mute_toggle() -> None: ...
def volume_mute_on() -> None: ...
def volume_mute_off() -> None: ...
def volume_mute_status(): ...
def microphone_mute_toggle() -> None: ...
