from ebenezer.commands.helpers import run_command as run_command

def cli() -> None: ...
def level() -> None: ...
def up() -> None: ...
def down() -> None: ...
def mute_toggle() -> None: ...
def mute_on() -> None: ...
def mute_off() -> None: ...
def mute_status() -> None: ...
