environment:
  modkey: mod4
  terminal: kitty
  browser: firefox
  wallpaper_dir: /home/foo/wallpapers
  wallpaper_timeout: 60
  os_logo: /home/foo/logos/linux.svg
  theme: ebenezer
  os_logo_icon: 󰌽
  os_logo_icon_color: "fg_purple"
  weather_api_key: foo
  city_id: 1
  rofi_home: /home/foo/.config/qtile/rofi
  scripts: /home/foo/.config/qtile/scripts

groups:
  browsers: 
  terminal:  
  editors: 󰘐
  games:   
  files: 󰉋
  win: 󰍲    

groups_layout:
  default: monadtall
  win: tile

startup:
  keyboard_layout: setxkbmap -model abnt2 -layout br && localectl set-x11-keymap br
  dunst: pkill dunst && dunst &


commands:
  screenshot: flameshot gui --clipboard --path ~/Pictures/Screenshots
  screenshot_full: flameshot full --clipboard --path ~/Pictures/Screenshots
  change_wallpaper: echo 'change wallpaper'

floating:
  wm_class:
    - pavucontrol
    - gnome-calculator
  title: []

fonts:
  font: Fira Code Nerd Font Bold
  font_regular: Fira Code Nerd Font Medium
  font_light: Fira Code Nerd Font Light
  font_strong: Fira Code Nerd Font Semibold
  font_strong_bold: Fira Code Nerd Font Bold
  font_icon: Fira Code Nerd Font Medium
  font_size: 14
  font_icon_size: 16

colors:
  fg_normal: "#D8DEE9"
  fg_focus: "#C4C7C5"
  fg_urgent: "#CC9393"
  bg_normal: "#263238"
  bg_focus: "#1E2320"
  bg_urgent: "#424242"
  bg_systray: "#37444b"
  bg_selected: "#5c6b73"
  fg_blue: "#304FFE"
  fg_light_blue: "#B3E5FC"
  fg_yellow: "#FFFF00"
  fg_red: "#D50000"
  fg_orange: "#FFC107"
  fg_purple: "#AA00FF"
  fg_green: "#4BC1CC"
  fg_gray: "#9db4c0"
  fg_white: "#ffffff"
  fg_black: "#000000"
  bg_topbar: "#282a36"
  bg_topbar_selected: "#6200EA"
  bg_topbar_arrow: "#5c6b73"
  border_color_normal: "#AA00FF"
  border_color_active: "#6200EA"
  border_color_marked: "#c678dd"
  titlebar_bg_focus: "#263238"
  titlebar_bg_normal: "#253238"
  taglist_bg_focus: "#37474F"
  group_focus: "#e0fbfc"
  group_normal: "#C4C7C5"
  lock_screen_blank_color: "#00000000"
  lock_screen_clear_color: "#ffffff22"
  lock_screen_default_color: "#9db4c0"
  lock_screen_key_color: "#8a8ea800"
  lock_screen_text_color: "#4BC1CC"
  lock_screen_wrong_color: "#D50000"
  lock_screen_verifying_color: "#41445800"
  lock_screen_quote_foreground_color: "#000"
  lock_screen_quote_text_color: "#fff"

lock_screen:
  command: ~/.config/qtile/lock.py
  timeout: 10
  font_size: 40
  font: Mononoki Nerd Font Bold
  quote_font_size: 17
  quote_font_path: /usr/share/fonts/TTF/MononokiNerdFont-Regular.ttf
  quote_font_path_alt: /usr/share/fonts/liberation/LiberationMono-Bold.ttf
  joke_providers: reddit,icanhazdad
  icanhazdad_joke_url: https://icanhazdadjoke.com/
  reddit_joke_url: https://www.reddit.com/r/ProgrammerDadJokes.json
  blurtype: "0x7"

monitoring:
  default_color: 'fg_normal'
  high_color: 'fg_orange'
  medium_color: 'fg_yellow'
  threshold_medium: 70
  threshold_high: 90
  burn: yes


bar:
  position: 'top'
  widgets:
    - type: 'group_box'
      margin_y: 3
      margin_x: 3
      padding: 3
      borderwidth: 3
      active: fg_normal
      inactive: fg_normal
      this_current_screen_border: bg_topbar_selected
      this_screen_border: fg_blue
      other_current_screen_border: bg_topbar_selected
      highlight_color: bg_topbar_selected
      highlight_method: text
      foreground: fg_normal
      rounded: false
      urgent_alert_method: border
      urgent_border: fg_urgent
    - type: 'separator'
    - type: 'current_layout'

