name: Deploy Documentation to Read the Docs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    - name: Build Documentation Locally
      run: |
        make html

    - name: Trigger RTD Build
      env:
        READTHEDOCS_TOKEN: ${{ secrets.READTHEDOCS_TOKEN }}
      run: |
        curl -X POST -d "" -H "Authorization: Token $READTHEDOCS_TOKEN" \
        https://readthedocs.org/api/v3/projects/<project-slug>/builds/
